services:
  todos_rust_app:
    container_name: todos_rust_app
    build:
      context: ./app
      target: dev
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@todos_db:5432/example
    volumes:
      - ./app:/my_app
    ports:
      - 3000:3000
    depends_on:
      - todos_db

  todos_db:
    container_name: todos_db
    image: postgres:17.1-alpine
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
    volumes:
      - ./app/migrations/20241229103554_init_todos_table.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./db_data:/var/lib/postgresql/data
