{
 "title": "rust_app_metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Rust application metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP requests per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "{{method}} {{path}}" }
   ]
  },
  {
   "title": "Mean response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_response_time_seconds_sum[5m]) / rate(http_response_time_seconds_count[5m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests number for the last minute",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_requests_total{method=\"GET\",path=\"/planets\"}[1m])"
    }
   ]
  },
  {
   "title": "Response time distribution over time (`GET /planets`)",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(http_response_time_seconds_bucket{path=\"/planets\"}[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Connected SSE clients",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_connected_sse_clients" }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"rust_app\"}[1m])",
     "legendFormat": "process"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name='rust_app'}[1m])) by (name)",
     "legendFormat": "container"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"rust_app\"} / 1024 / 1024",
     "legendFormat": "process"
    },
    {
     "expr": "container_memory_usage_bytes{name=\"rust_app\"} / 1024 / 1024",
     "legendFormat": "container"
    }
   ]
  }
 ]
}